# Site settings
course_name: Intro to Data Structures and Algorithms
course_description: "My fake DSA course so I can have a better thing. "
course_semester: "Spring 2025"

baseurl: "/dsa-course-explore" # the subpath of your site, e.g. /blog/
url: "http://jumping-blocks.github.io/" # the base hostname & protocol for your site

schoolname: "University of Washington"
schoolurl: "https://washington.edu"
twitter_username: username 

address: |
    ECE PMP
    UW
    Seattle, WA

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false
    notes:
        output: true


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
